import Head from 'next/head'
import {client} from "@/lib/data";
import PortfolioItem from "@/components/PortfolioItem";
// import styles from '@/styles/Home.module.css'

export default function Home(props) {
	console.log(props);
	const {portfolioItems} = props;
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app"/>
				<meta name="viewport" content="width=device-width, initial-scale=1"/>
				{/*<link rel="icon" href="/favicon.ico"/>*/}
			</Head>
			<main className={'bg-black text-gray-200 min-h-screen py-8'}>
				<section className={'container mx-auto px-4 mb-8'}>
					<div className="flex flex-col py-12 justify-center min-h-[25vh]">
						<div className="flex-shrink inline-flex flex-col w-fit">
							<h1 className={'flex-shrink mr-12 text-5xl md:text-6xl'}>Tilemachos Pothitos</h1>
							<h2 className={'ml-6 sm:ml-auto text-xl'}>Front-End Developer</h2>
						</div>
					</div>
				</section>
				<section className={'container mx-auto px-4 mb-8'}>
					<div className="flex flex-col py-12 justify-center min-h-[25vh]">
						<h2 className={'mb-8'}>
							Work
						</h2>
						<div className="ml-6 grid gap-6">
							{
								portfolioItems.map(item => {
									const {_id: id, title, slug: { current: slug }, description, category: categories} = item;
									return (
										<div key={id}>
											<PortfolioItem slug={slug} title={title} description={description} categories={categories}/>
										</div>
									)
								})
							}
						</div>
					</div>
				</section>
				<section className={'container mx-auto px-4 mb-8'}>
					<div className="flex flex-col py-12 justify-center min-h-[25vh]">
						<h2 className={'mb-2'}>
							Contact
						</h2>
						<div className="ml-6">
							<a href="mailto:tilpoth@gmail.com">tilpoth@gmail.com</a>
						</div>
					</div>
				</section>
			</main>
		</>
	)
}

export async function getStaticProps() {
	const portfolioItems = await client.fetch(`*[_type=='portfolioItem']{_id, title, slug, description, category[]->{_id, title, slug}}`);
	return {
		props: {
			portfolioItems
		}
	};
}
